<!DOCTYPE html>
<html>
<head>
    <title>Online shop</title>
</head>
<body>
<h1>Online shop</h1><hr>
<h4>Authorization</h4>
<form action="/login" method="post">
    E-mail: <input type="email" name="username"><br><br>
    password: <input type="password" name="password"><br><br>
    <input type="hidden" name="hidden" value="hid" >
    <input type="submit" value="Вход"/>
</form>
<a href="/registration">Registration</a>
</body>
</html>
